apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS reviews (
      name TEXT,
      review TEXT
    );

    INSERT INTO reviews (name, review) VALUES
    ('Ada Lovelace', 'Imagine tu supprimes le pod de VS Code sans faire exprès'),
    ('Alan Turing', 'Nan je rigole'),
    ('Grace Hopper', 'Mais imagine quand même'),
    ('Linus Torvalds', 'Oh non j ai tué Python!');